### ISSUE TITLE
TypeError when bootstrapping vuetify-admin with Vue CLI

### ISSUE THREAD

**Issue by matthewlynden** [okami101/vuetify-admin#4]
**Describe the bug**
This issue is related to bootstrapping a new project using the Vue CLI.
After answering the prompts in Vue CLI during project setup a ```TypeError: Cannot read property 'includes' of undefined``` is returned.

**To Reproduce**

1. nvm use 10.23.0
2. npm install -g @vue/cli
3. vue create my-admin-project --preset okami101/vuetify-admin-preset
4. complete prompts (as per screenshot attached)

**Screenshots**
https://ibb.co/MDjXNnZ

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser: Chrome 86.0.4240.183
- Vue CLI version: 4.5.8
- NPM Packages: Vue 2.6.12

**Comment by adr1enbe4udou1n** [comment]
Fixed on 0.5.7
Thx for feedback !
