### ISSUE TITLE
Is this still an active project?

### ISSUE THREAD

**Issue by blafasel42** [okami101/vuetify-admin#40]
**Disclaimer**
Be sure to use the last Vue CLI 4.x version before create the issue.

**Describe the bug**

We had many issues. Like: Edit did not work at all. It fetches data from the API but does not put it in the store.
Also: we tried to add external URL to navigation but it does not work. We do not see code for doing what was described in the documentation.

I wonder if this project is ready for use and if it is actively maintained.

**Comment by adr1enbe4udou1n** [comment]
Hello Gaylord,

As you seen with last commit date (4 months…) I clearly give up maintenance of this project. It becomes completely outdated with next release of Vuetify 3 version which will force full rewrite and I have no time anymore for such a big rework.

I can only redirect you to https://github.com/marmelab/react-admin which is a far best maintained alternative.
